version: 2
jobs:
  build:
    docker:
      - image: dougley/crowdin:latest
    steps:
      - checkout
      - run:
          name: Crowdin upload
          command: crowdin upload sources
workflows:
  version: 2
  crowdin:
    jobs:
      - build
