version: 2
jobs:
  build:
    docker:
      - image: dougley/crowdin:latest
    steps:
      - checkout
      - run:
          name: Rename source file
          command: mv en.json source.json
      - run:
          name: Crowdin upload
          command: crowdin upload sources -b WildBeast
workflows:
  version: 2
  crowdin:
    jobs:
      - build
